:base_url = http://localhost:4000
##

POST :base_url/api/topics
Content-Type: application/json

{
	"topic": {
		 "title": ""
	}
}

##
GET :base_url/api/topics

##
GET :base_url/api/topics/3

##
PUT :base_url/api/topics/1
Content-Type: application/json

{
	"topic": {
		 "title": "bla bla asdas"
	}
}
